Update patch set 1
Patch Set 1: Code-Review+1

Consider a test, it seems like a weird case. Especially because one-arg unicode() works differently:

>>> unicode(unicode('x'))
u'x'

>>> unicode(unicode('x'), errors='replace')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: decoding Unicode is not supported

Patch-set: 1
Reviewer: smut <1003211@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=+1